language: generic

services:
  - docker

env:
  global:
    - REPO=docksal/cli
    - LATEST_VERSION=7.2
    - DOCKSAL_VERSION=master
  matrix:
    - VERSION=5.6
    - VERSION=7.0
    - VERSION=7.1
    - VERSION=7.2

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libfcgi0ldbl  # cgi-fcgi binary used in tests

install:
  - curl -fsSL https://get.docksal.io | DOCKSAL_VERSION=${DOCKSAL_VERSION} bash
  - fin version
  - fin sysinfo

script:
  # Build the base image
  - cd ${TRAVIS_BUILD_DIR}/${VERSION}
  - travis_retry make && make test  # Retry builds, as pecl.php.net tends to time out often
  # Build the Cloud9 flavor
  - cd ${TRAVIS_BUILD_DIR}/cloud9
  - travis_retry make && make test

after_success:
  - docker image ls
  - scripts/docker-push.sh

after_failure:
  - cd ${TRAVIS_BUILD_DIR}/${VERSION} && make logs
  - cd ${TRAVIS_BUILD_DIR}/cloud9 && make logs
